// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus int32

const (
	TransactionStatus_APPROVED TransactionStatus = 0
	TransactionStatus_PENDING  TransactionStatus = 1
	TransactionStatus_DECLINED TransactionStatus = 2
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "APPROVED",
		1: "PENDING",
		2: "DECLINED",
	}
	TransactionStatus_value = map[string]int32{
		"APPROVED": 0,
		"PENDING":  1,
		"DECLINED": 2,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_proto_transaction_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SenderId              string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderAccountId       string                 `protobuf:"bytes,3,opt,name=sender_account_id,json=senderAccountId,proto3" json:"sender_account_id,omitempty"`
	SenderAccountNumber   string                 `protobuf:"bytes,4,opt,name=sender_account_number,json=senderAccountNumber,proto3" json:"sender_account_number,omitempty"`
	ReceiverId            string                 `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ReceiverAccountId     string                 `protobuf:"bytes,6,opt,name=receiver_account_id,json=receiverAccountId,proto3" json:"receiver_account_id,omitempty"`
	ReceiverAccountNumber string                 `protobuf:"bytes,7,opt,name=receiver_account_number,json=receiverAccountNumber,proto3" json:"receiver_account_number,omitempty"`
	Amount                float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Status                TransactionStatus      `protobuf:"varint,10,opt,name=status,proto3,enum=transaction.TransactionStatus" json:"status,omitempty"`
	Note                  string                 `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	PaymentCode           string                 `protobuf:"bytes,12,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	Model                 string                 `protobuf:"bytes,13,opt,name=model,proto3" json:"model,omitempty"`
	CallNumber            string                 `protobuf:"bytes,14,opt,name=call_number,json=callNumber,proto3" json:"call_number,omitempty"`
	CreatedAt             string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Transaction) GetSenderAccountId() string {
	if x != nil {
		return x.SenderAccountId
	}
	return ""
}

func (x *Transaction) GetSenderAccountNumber() string {
	if x != nil {
		return x.SenderAccountNumber
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetReceiverAccountId() string {
	if x != nil {
		return x.ReceiverAccountId
	}
	return ""
}

func (x *Transaction) GetReceiverAccountNumber() string {
	if x != nil {
		return x.ReceiverAccountNumber
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_APPROVED
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Transaction) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *Transaction) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Transaction) GetCallNumber() string {
	if x != nil {
		return x.CallNumber
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateTransactionRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SenderAccountNumber   string                 `protobuf:"bytes,1,opt,name=sender_account_number,json=senderAccountNumber,proto3" json:"sender_account_number,omitempty"`
	ReceiverAccountNumber string                 `protobuf:"bytes,2,opt,name=receiver_account_number,json=receiverAccountNumber,proto3" json:"receiver_account_number,omitempty"`
	Amount                float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency              string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Note                  string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	PaymentCode           string                 `protobuf:"bytes,6,opt,name=payment_code,json=paymentCode,proto3" json:"payment_code,omitempty"`
	Model                 string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	CallNumber            string                 `protobuf:"bytes,8,opt,name=call_number,json=callNumber,proto3" json:"call_number,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetSenderAccountNumber() string {
	if x != nil {
		return x.SenderAccountNumber
	}
	return ""
}

func (x *CreateTransactionRequest) GetReceiverAccountNumber() string {
	if x != nil {
		return x.ReceiverAccountNumber
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateTransactionRequest) GetPaymentCode() string {
	if x != nil {
		return x.PaymentCode
	}
	return ""
}

func (x *CreateTransactionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateTransactionRequest) GetCallNumber() string {
	if x != nil {
		return x.CallNumber
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByUserRequest) Reset() {
	*x = GetTransactionsByUserRequest{}
	mi := &file_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByUserRequest) ProtoMessage() {}

func (x *GetTransactionsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTransactionsByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByUserResponse) Reset() {
	*x = GetTransactionsByUserResponse{}
	mi := &file_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByUserResponse) ProtoMessage() {}

func (x *GetTransactionsByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByUserResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionsByUserResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_proto_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x17proto/transaction.proto\x12\vtransaction\"\x9c\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12*\n" +
	"\x11sender_account_id\x18\x03 \x01(\tR\x0fsenderAccountId\x122\n" +
	"\x15sender_account_number\x18\x04 \x01(\tR\x13senderAccountNumber\x12\x1f\n" +
	"\vreceiver_id\x18\x05 \x01(\tR\n" +
	"receiverId\x12.\n" +
	"\x13receiver_account_id\x18\x06 \x01(\tR\x11receiverAccountId\x126\n" +
	"\x17receiver_account_number\x18\a \x01(\tR\x15receiverAccountNumber\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x126\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2\x1e.transaction.TransactionStatusR\x06status\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12!\n" +
	"\fpayment_code\x18\f \x01(\tR\vpaymentCode\x12\x14\n" +
	"\x05model\x18\r \x01(\tR\x05model\x12\x1f\n" +
	"\vcall_number\x18\x0e \x01(\tR\n" +
	"callNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\"\xa8\x02\n" +
	"\x18CreateTransactionRequest\x122\n" +
	"\x15sender_account_number\x18\x01 \x01(\tR\x13senderAccountNumber\x126\n" +
	"\x17receiver_account_number\x18\x02 \x01(\tR\x15receiverAccountNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x12!\n" +
	"\fpayment_code\x18\x06 \x01(\tR\vpaymentCode\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x1f\n" +
	"\vcall_number\x18\b \x01(\tR\n" +
	"callNumber\"W\n" +
	"\x19CreateTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.transaction.TransactionR\vtransaction\"7\n" +
	"\x1cGetTransactionsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x1dGetTransactionsByUserResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.transaction.TransactionR\ftransactions*<\n" +
	"\x11TransactionStatus\x12\f\n" +
	"\bAPPROVED\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\f\n" +
	"\bDECLINED\x10\x022\xe8\x01\n" +
	"\x12TransactionService\x12b\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a&.transaction.CreateTransactionResponse\x12n\n" +
	"\x15GetTransactionsByUser\x12).transaction.GetTransactionsByUserRequest\x1a*.transaction.GetTransactionsByUserResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_proto_rawDescData []byte
)

func file_proto_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_proto_rawDescData
}

var file_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_transaction_proto_goTypes = []any{
	(TransactionStatus)(0),                // 0: transaction.TransactionStatus
	(*Transaction)(nil),                   // 1: transaction.Transaction
	(*CreateTransactionRequest)(nil),      // 2: transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil),     // 3: transaction.CreateTransactionResponse
	(*GetTransactionsByUserRequest)(nil),  // 4: transaction.GetTransactionsByUserRequest
	(*GetTransactionsByUserResponse)(nil), // 5: transaction.GetTransactionsByUserResponse
}
var file_proto_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.Transaction.status:type_name -> transaction.TransactionStatus
	1, // 1: transaction.CreateTransactionResponse.transaction:type_name -> transaction.Transaction
	1, // 2: transaction.GetTransactionsByUserResponse.transactions:type_name -> transaction.Transaction
	2, // 3: transaction.TransactionService.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	4, // 4: transaction.TransactionService.GetTransactionsByUser:input_type -> transaction.GetTransactionsByUserRequest
	3, // 5: transaction.TransactionService.CreateTransaction:output_type -> transaction.CreateTransactionResponse
	5, // 6: transaction.TransactionService.GetTransactionsByUser:output_type -> transaction.GetTransactionsByUserResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_transaction_proto_init() }
func file_proto_transaction_proto_init() {
	if File_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_proto_rawDesc), len(file_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_proto_depIdxs,
		EnumInfos:         file_proto_transaction_proto_enumTypes,
		MessageInfos:      file_proto_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_proto = out.File
	file_proto_transaction_proto_goTypes = nil
	file_proto_transaction_proto_depIdxs = nil
}
